---
apiVersion: v1
kind: Service
metadata:
  name: zalenium
  namespace: default
  labels:
    app: zalenium
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4444
  selector:
    app: zalenium
    role: grid
